version: "2"
services:
  web:
    command: npm run start-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  mongo:
    image: mongo
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"